#!/bin/sh
DIR="$(date +"%Y-%m-%d")"
mkdir $DIR
cat >$DIR/note.tex << EOF
\\documentclass[12pt]{article}
\\usepackage{parskip}
\\usepackage{enumerate}
\\usepackage{listings}
\\usepackage{fullpage}

\\begin{document}

\\title{PSYCH 101}
\\author{Matthew Visser}
\\date{`date +"%b %e, %Y"`}
\\maketitle

\\end{document}
% vim: tw=80
EOF



